### ISSUE TITLE
Add support for Unifi Smart Power devices

### ISSUE THREAD

**Issue by starsoccer** [Kane610/aiounifi#122]
Creating ticket as requested here, https://github.com/home-assistant/core/issues/71531

Let me know what info you need. Happy to provide whatever is needed. Will just mention there are(as far as Im aware 2 different devices),
Single Outlet: https://store.ui.com/collections/unifi-accessories/products/unifi-smart-power
Strip: https://store.ui.com/collections/unifi-accessories/products/smartpower-strip

I have both of them(2 outlets, and 1 strip) so can provide whatever information is needed on either in case they different slightly

**Comment by Kane610** [comment]
Thank you, this is not nearly enough information to support them though. Could you perhaps share a diagnostics file from the UniFi integration as a start?

**Comment by starsoccer** [comment]
Sure, diagnostics file attached

[config_entry-unifi-1eabc036c156a091a334f15b0fad5845.json.txt](https://github.com/Kane610/aiounifi/files/8681769/config_entry-unifi-1eabc036c156a091a334f15b0fad5845.json.txt)

**Comment by Kane610** [comment]
Right now I'm reworking the implementation do I try to avoid expanding it at the moment. It shouldn't take too long though I don't know if I'll have a pause during my summer vacation

**Comment by starsoccer** [comment]
Any update to this?

**Comment by Kane610** [comment]
Before expanding this Im doing some generic rewrites that will benefit future development. So no explicit ETA, maybe with 2022.10 but can't promise that

**Comment by stephack** [comment]
Thanks for your continued work on this @Kane610 .
I also have the SmartPower PDU if you ever needed to test or obtain any information from this unit.

**Comment by stephack** [comment]
After playing around with the Unifi API a little and doing some digging I came across this example of controlling the power outlets on a SmartPower PDU.

https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/modify_smartpower_pdu_outlet.php

Hopefully this helps as you continue to update the Unifi integrations.

**Comment by rhdny** [comment]
Good find. Thanks! Hope we can get it build into the UniFi integration at some point :)

**Comment by Kane610** [comment]
The Rewrite is going well, but I still won't promise an ETA though

**Comment by starsoccer** [comment]
Just wanted to note as of an update(not sure as to when) it does seem possible to control these devices(atleast the smart outlet and strip). They appear in home assistant now with toggles for the power.

**Comment by stephack** [comment]
> Just wanted to note as of an update(not sure as to when) it does seem possible to control these devices(atleast the smart outlet and strip). They appear in home assistant now with toggles for the power.

I just updated to 2022.12.8 but don't have any entities that allow me to control the outlets on the smartPDU yet. Good to see there is progress though.

**Comment by starsoccer** [comment]
> Another feature request https://community.home-assistant.io/t/support-for-usp-pdu-pro-in-the-ubiquity-integration/550746

Can confirm for PDU I can not seem to control things. Single plug and strip still work fine for me

**Comment by starsoccer** [comment]
Just bumping this. Would be great if PDU got added along with power consumption metrics

**Comment by legomind** [comment]
I can perform any testing needed on the USP-PDU-Pro. Would love to see power consumption and relay switches in ha.

**Comment by Cisien** [comment]
> Just bumping this. Would be great if PDU got added along with power consumption metrics

I've submitted a PR for this feature: https://github.com/home-assistant/core/pull/98081

![image](https://github.com/Kane610/aiounifi/assets/4044356/27c1cf8b-7497-453b-a809-4b6047d11ed4)

**Comment by starsoccer** [comment]
Awesome glad to see this being done. Looks great. Cant wait for it to be merged.

Happy to help test anything if needed. I have most of the smart power devices

**Comment by Kane610** [comment]
> Awesome glad to see this being done. Looks great. Cant wait for it to be merged.
> 
> Happy to help test anything if needed. I have most of the smart power devices

Its merged so available on dev shortly :)

**Comment by Cisien** [comment]
so, i think the change i'm proposing in https://github.com/Kane610/aiounifi/issues/427 would magically start supporting PDU outlet switches, as well as letting us update the change I made in that PR to use the more self-documenting properties instead of a "caps" bitfield.

Also, I just added a new PR for reading the AC outlet budget/consumption metrics

**Comment by Cisien** [comment]
That's exactly what it will do!
![image](https://github.com/Kane610/aiounifi/assets/4044356/3d3ed382-9d78-4a12-9beb-2da064f1f7d2)

**Comment by starsoccer** [comment]
😄 this is great I cant wait for it to hit main/release and use it

**Comment by Kane610** [comment]
We have merged @Cisien next PR with total power consu.ption of a pdu

**Comment by Kane610** [comment]
Just merged extended support for controlling outlet relays for PDUs. I think we can close this issue now.

**Comment by stephack** [comment]
Thanks for getting this added @Kane610 
We appreciate your commitment to this integration.

**Comment by Kane610** [comment]
> 

Thanks! But the kudos should go to @Cisien who put in the effort :)

**Comment by stephack** [comment]
> > 
> 
> Thanks! But the kudos should go to @Cisien who put in the effort :)

Updated my kudos accordingly 😉

**Comment by Cisien** [comment]
Thanks! Let me know if you run into any issues!

I'm guessing this is in the pipeline for the August (September?) release?

**Comment by Kane610** [comment]
> I'm guessing this is in the pipeline for the August (September?) release?

Yes the beta will be on the 30th of August

**Comment by Kane610** [comment]
Beta is out and we can consider this issue completed. Thanks for your excellent contribution @Cisien
