### ISSUE TITLE
Switch to enable and disable Wifi networks of the UniFi controller

### ISSUE THREAD

**Issue by MagoPoza** [Kane610/aiounifi#181]
I think a switch would be a good tool to be able to activate or deactivate a Wi-Fi network from the UniFi controller, being able to do it from Home Assistant without having to access the UniFi controller

![unifi](https://user-images.githubusercontent.com/63115455/189409899-afbe5e63-6867-412c-aa2d-8a0e55868f46.png)

**Comment by deathbybandaid** [comment]
I have a use-case for this as well. I need my wife to be easily able to pause/resume the wifi ssid for our foster kids.

I could then get a physical switch or a nfc tag setup to toggle this when I'm not home.

**Comment by spbrogan** [comment]
I would really like to see this too.

**Comment by mefistofelis** [comment]
Yeah that would be cool

**Comment by Kane610** [comment]
https://community.home-assistant.io/t/enable-or-disable-a-unifi-wifi-network-via-switch-in-home-assistant/61787/40

**Comment by Kane610** [comment]
PR is up https://github.com/home-assistant/core/pull/97204 unsure if it will make tomorrows beta cut off.
