### ISSUE TITLE
Switch to reboot unifi devices available in controller

### ISSUE THREAD

**Issue by MagoPoza** [Kane610/aiounifi#184]
Sometimes after power outages I have to restart the device for some cameras to reconnect.
It would be great if it could be done with a switch from Home Assistant so you don't have to access the controller.

![Unifi](https://user-images.githubusercontent.com/63115455/190001432-3189afc7-8dd8-4180-a85a-420af7e2428a.PNG)

**Comment by Kane610** [comment]
Thanks! I'll have a look

**Comment by Kane610** [comment]
This will be supported from HA 2023.9 release.

**Comment by eikowagenknecht** [comment]
@Kane610 @MagoPoza How can this be done? In HA (2023.11.0b0) I only see the following two services:

![image](https://github.com/Kane610/aiounifi/assets/1475672/14d29613-8f4a-4ef3-b7ea-d0145074fd37)

And no buttons for reboot in the AP device either:

![image](https://github.com/Kane610/aiounifi/assets/1475672/8a048e10-8a78-4cb8-94da-632f0c27d144)

**Comment by Kane610** [comment]
> @Kane610 @MagoPoza How can this be done? In HA (2023.11.0b0) I only see the following two services:
> 
> ![image](https://user-images.githubusercontent.com/1475672/278325644-14d29613-8f4a-4ef3-b7ea-d0145074fd37.png)
> 
> And no buttons for reboot in the AP device either:
> 
> ![image](https://user-images.githubusercontent.com/1475672/278325856-8a048e10-8a78-4cb8-94da-632f0c27d144.png)

Have you provided credentials with admin access?

**Comment by eikowagenknecht** [comment]
Oh wow, the user apparently only had reading rights for the network... Switched to Super Admin role and now the restart buttons are there. Thank you!

**Comment by Kane610** [comment]
> Oh wow, the user apparently only had reading rights for the network... Switched to Super Admin role and now the restart buttons are there. Thank you!

Awesome!
