### ISSUE TITLE
Home Assist 2022.10b0 triggered Unsupported event key EVT_IPS_IpsAlert

### ISSUE THREAD

**Issue by jasperslits** [Kane610/aiounifi#195]
Since upgrade of HA to 2022.10b0 (released yesterday), I see warnings I haven't seen before:

2022-09-29 09:07:07.847 WARNING (MainThread) [aiounifi.models.event] Unsupported event key EVT_IPS_IpsAlert

It's not defined here: https://github.com/Kane610/aiounifi/blob/master/aiounifi/models/event.py

Unifi controller version: 7.3.69
Controller hasn't been upgraded since switching to 2022.10.0b0 and is latest available.

**Comment by Kane610** [comment]
Thanks for reporting!

I have an open PR to fix this https://github.com/Kane610/aiounifi/pull/194

Aim to get it into ha in the weekend

**Comment by Kane610** [comment]
Library is updated and PR for Home Assistant is published (https://github.com/home-assistant/core/pull/79487). Thanks for reporting!
