### ISSUE TITLE
Home Assist 2022.10.0b3 triggered Unsupported event key EVT_AP_PossibleInterference

### ISSUE THREAD

**Issue by jasperslits** [Kane610/aiounifi#197]
Similar to #195, I noticed  EVT_AP_PossibleInterference warning with 2022.10.0b3 

I guess there might be more warnings as it seems to depend on what conditions the controller encounter, e.g. misbehaving APs, so may seem a matter of time before new ones pop up?

i couldn’t tell from HA entities where the event values are exposed to.

**Comment by Kane610** [comment]
Thanks! Far from all events are used today, but this helps expanding what events exist.

**Comment by jasperslits** [comment]
https://pkg.go.dev/github.com/telunifi/unifi Has a few more for evt_ap_xx, e.g. the upgradescheduled one. 
no idea how complete it is though

**Comment by Kane610** [comment]
Thanks! I'll go through it and add any differences before Tuesday!

**Comment by Kane610** [comment]
Fixed in HA 2022.10
