### ISSUE TITLE
Unsupported event key EVT_AD_ScheduleUpgradeFailedNotFound

### ISSUE THREAD

**Issue by jasperslits** [Kane610/aiounifi#234]
This appeared in the logs today. I am running 2022.11.0b3 of HA and latest Unify stack. 

Unsupported event key EVT_AD_ScheduleUpgradeFailedNotFound
Unsupported event {'mac': '74:ac:b9:0b:07:1b', 'key': 'EVT_AD_ScheduleUpgradeFailedNotFound', 'subsystem': '', 'is_negative': True, 'site_id': '60dee48f6573ae03e1f837d7', 'time': 1667174700004, 'datetime': '2022-10-31T00:05:00Z', 'msg': 'Device 74:ac:b9:0b:07:1b not found for firmware upgrade', '_id': '635f112c01899308de7cf128'}

I have no idea what kind of device 74:ac:b9:0b:07:1b is and there are no logs in the UDM Pro console, but it showed up in the HA logs as a new event.

**Comment by Kane610** [comment]
You sure you don't find anything with that serial number?

**Comment by jasperslits** [comment]
Turned out it was the G4 Doorbell after some searching again. The doorbell works fine so it's not clear where it's coming from. 

I guess device updates for Protect managed devices are not coming from the Network app. 
But it's the first time I've seen the message in the logs, so might be some disturbance in space-time as manual check for updates in Unify Network app doesn't create another entry in the HA logs. So for now not possible to reproduce and doesn't seem to point to a real problem.

**Comment by jasperslits** [comment]
Upon checking the release. AD_SCHEDULE_UPGRADE_FAILED_NOT_FOUNT Has a typo. Should be FOUND instead of FOUNT.

**Comment by Kane610** [comment]
Thanks!
