### ISSUE TITLE
Unsupported event keys

### ISSUE THREAD

**Issue by elektr0nisch** [Kane610/aiounifi#312]
Hi there,

I'm using the UniFi-Network integration in HomeAssistant and encounter warning messages in my system's logs which, i suppose, originate from unsupported event keys! Due to the fact that the logger logging this message is `aiounifi.models.event` I thought this might be a problem of the underlying library, not HA core - so here I am!

The messages I get are:

``
Unsupported event {'guest': '<guest_mac>', 'key': 'EVT_WG_AuthorizationEnded', 'subsystem': 'wlan', 'is_negative': False, 'site_id': '<site_id>', 'time': 1677593579225, 'datetime': '2023-02-28T14:12:59Z', 'msg': 'Guest[<guest_mac>] has become unauthorized', '_id': '63fe0beb4a36f60dcf25a3da'}
``

... and: 

``
Unsupported event {'code': '<voucher_used>', 'guest': '<guest_mac>', 'key': 'EVT_HS_VoucherUsed', 'subsystem': 'wlan', 'is_negative': False, 'site_id': '<site_id>', 'time': 1677591001035, 'datetime': '2023-02-28T13:30:01Z', 'msg': 'Voucher[<voucher_used>] was used by Guest[<guest_mac>]', '_id': '63fe01d94a36f60dcf257c78'}
``

It seems as if this library is currently not supporting the events `EVT_WG_AuthorizationEnded` and `EVT_HS_VoucherUsed`. 
I would love it, if anybody with more knowledge in python than I have, could implement those events!

Thanks a lot! ❤

Kind regards
Linus

**Comment by Kane610** [comment]
Thank you!
