### ISSUE TITLE
Unsupported event key EVT_DM_Connected

### ISSUE THREAD

**Issue by jasperslits** [Kane610/aiounifi#361]
A new warning was showing up which I haven't seen before. I don't recall what was going on and don't see any errors in the Unifi console logs. It's running Unifi OS 3.0.19 beta firmware and Unifi network 7.4.146

Unsupported event key EVT_DM_Connected
Unsupported event {'key': 'EVT_DM_Connected', 'dm': '74:ac:b9:XX:XX:XX', 'gw': '74:ac:b9:XX:XX:XX, 'dm_name': 'UDM XXX', 'dm_model': 'UDMPRO', 'dm_displayName': 'UDM Huysackers', 'gw_displayName': 'UDM XXX', 'subsystem': 'lan', 'is_negative': False, 'site_id': '60dee48f657XXX7', 'time': 1681829649586, 'datetime': '2023-04-18T14:54:09Z', 'msg': '74:ac:b9::XX:XX:XX was connected', '_id': '643eaf127ccaa6694XXXXX'}

Upon googling, it's mentioned in https://github.com/home-assistant/core/issues/84251 but couldn't find any other occurrence.

**Comment by Kane610** [comment]
Thanks!

**Comment by Kane610** [comment]
PR is up, should be a part of 2023.5 release

https://github.com/home-assistant/core/pull/91966
