### ISSUE TITLE
outlet_caps relating to feature availability

### ISSUE THREAD

**Issue by Cisien** [Kane610/aiounifi#427]
Posting this to discuss the meaning of outlet_caps.

The data I have so far:
On the USP-Plug: no outlet_caps property is available
On the USP-PDU-Pro: the outlet_caps property is available on each outlet in the outlet_table
For USB ports, the value is 1
For Power outlets, the value is 3

USP-Plug has properties called `has_metering` and `has_relay` to convey the capabilities of that device
USP-PDU-Pro does not have these convenient properties, instead the outlets have a `outlet_caps` property.

| Capability Flag                  | Meaning                         |
|----------------------------------|---------------------------------|
| 1                                | Supports Switching              |
| 2 (not seen on a device yet)     | Supports metering               |
| 3                                | Supports Switching and Metering |

**Comment by Kane610** [comment]
I think its sound to define it like this!

**Comment by Cisien** [comment]
What are your thoughts on "shimming" these caps definitions into the expected properties?

for example:
```py
    @property
    def has_relay(self) -> bool | None:
        """Is the outlet controllable."""
        has_relay = self.raw.get("has_relay")
        if has_relay = None:
            outlet_caps = self.raw.get("outlet_caps")
            has_relay = outlet_caps == 3 or outlet_caps == 1 
        return has_relay
```

uses the property that comes back from the API if it's available. if it's not, it uses caps to determine the result.

**Comment by Kane610** [comment]
> What are your thoughts on "shimming" these caps definitions into the expected properties?
> 
> for example:
> 
> ```python
>     @property
>     def has_relay(self) -> bool | None:
>         """Is the outlet controllable."""
>         has_relay = self.raw.get("has_relay")
>         if has_relay == None:
>             outlet_caps = self.raw.get("outlet_caps")
>             has_relay = outlet_caps == 3 or outlet_caps == 1 
>         return has_relay
> ```
> 
> uses the property that comes back from the API if it's available. if it's not, it uses caps to determine the result.

So right now Im not a fan of trying put too much logic into the library but rather try to keep it close to what the API exposes. I think its better we combine this data on the integration side of things.

**Comment by Cisien** [comment]
In that case, I'll update my PR to only document the caps
