### ISSUE TITLE
Help running tests

### ISSUE THREAD

**Issue by frank-783** [Kane610/aiounifi#50]
Hi, I have been using this library for some automations around my unifi controller and it is awesome. I was attempting to add some functionality and hit an issue running the test suite. when I run pytest I get the warning `async def functions are not natively supported` I see that asynio-0.14.0 is installed but the marker is not used on the tests. Is there a setup step that I missed? Sorry is this is an obvious question. Thank you!

Commands that I ran
```
pip install -r requirements_tests.txt
pytest
```

**Comment by Kane610** [comment]
Hey! Sorry I've totally missed this. My environment is not optimal so I don't actually know what dependency is missing here, maybe pytest-asyncio?

**Comment by Kane610** [comment]
I've added updated information about what dependencies are required for running tests
