### ISSUE TITLE
Adding Traffic routes

### ISSUE THREAD

**Issue by shaunpearsondev** [Kane610/aiounifi#522]
Hi @Kane610 

I am looking at adding functionality for Traffic routes to this library and would like to get some of your time to get your thoughs on this before I go ahead and code it all up, the functionality seems to be behind the v2 api (like traffic rules) 

Here is a very early draft:
https://github.com/bigwhitesolutions/aiounifi/commit/1ea853f83856188651736f30f6ae29844a972044

It has very simular models to traffic rules so wondering if these should be shared?

Thank you!

Shaun

**Comment by Kane610** [comment]
Hello and welcome!

Put up a PR and we can cooperate on the details. Skimmed through your linked code and from that quick glance it looked OK.

Let's keep all endpoints standalone as much as possible in case it changes later on. Keeping it explicit helps with future refactoring

**Comment by Kane610** [comment]
This is completed
