### ISSUE TITLE
Power Monitoring For Smart Power Strip

### ISSUE THREAD

**Issue by starsoccer** [Kane610/aiounifi#559]
Not really sure if this is supposed to be supported or not. It seems like on the UI App it shows power usage, but all values are zeroed out. So assuming it does support power monitoring is there any plan to add support for it?

**Comment by Kane610** [comment]
If the device has a power metering sensor it should also work, multple errors reported recently on unifi integration unfortunately.

**Comment by starsoccer** [comment]
How would I be able to confirm if it has power monitoring? It says remote monitoring here, and in the app shows power but its always zero, https://store.ui.com/us/en/products/usp-strip-us

**Comment by Kane610** [comment]
You should be able to determine it from the log output. If you enable debug logging for the integration you should be able to see if device and outlet has any properties related to power measurement

**Comment by starsoccer** [comment]
So I dug through the logs and it seems they all have `has_metering` set to false which I am guessing is what would determine if it can do power monitoring or not?

Partial dump from outlet tables,
```
"outlet_table"[{"has_relay":true,"cycle_enabled":false,"relay_state":true,"name":"TV","index":1,"has_metering":false,"outlet_caps":65537}
```

**Comment by Kane610** [comment]
"outlet_caps":65537}

A contributor earlier looked through the outlet_caps alternatives and concluded that "At this time, an outlet_caps value of 3 is expected to indicate that the outlet supports metering"

So I guess it does not support power metering

**Comment by starsoccer** [comment]
Okay thanks for checking
