### ISSUE TITLE
Add ability to activate/deactivate traffic rules

### ISSUE THREAD

**Issue by lensherm** [Kane610/aiounifi#560]
In the Unifi controller (UDMP in my case), there is a Traffic Rules section under Settings-->Security

As an example, I created a number of these rules block access to Youtube and separately online games on my kids' devices, but that's just an example.

Proceeding with my example, as I only want these rules to be enabled when the kids are doing their homework, I created some HA automations using the below in Node Red, but ideally, it would be nice to be able to have an on/off switch for each of the rules in the list in HA directly.
[[node-red-contrib-unifi](https://github.com/Isaksson/node-red-contrib-unifi)](url)

In Node Red the payload looks something like this:
`msg.payload = { command: "enableTrafficManagementRule", rule_id: "12345678901234567890" }`

where each rule is identified by it's unique rule_id

and the list of rules can be gotten by calling `getTrafficManagementRule`

**Comment by lensherm** [comment]
Upon further digging, it looks like this might have already been discussed in [https://github.com/Kane610/aiounifi/issues/323](url)

Regardless, it would be really nice to have this functionality

**Comment by Kane610** [comment]
It's being worked on here https://github.com/home-assistant/core/pull/104671

**Comment by lensherm** [comment]
Thank you! Much appreciated!

**Comment by lensherm** [comment]
Duplicate per the following PR [https://github.com/home-assistant/core/pull/104671](url)
