### ISSUE TITLE
JSONDecodeError: Input is a zero-length, empty document

### ISSUE THREAD

**Issue by bmos** [Kane610/aiounifi#589]
I get this in my logs after each update lately, although the integration seems to be working fine.

> Logger: aiounifi.interfaces.connectivity
> Source: /usr/local/lib/python3.12/site-packages/aiounifi/interfaces/connectivity.py:203
> First occurred: 8:51:02 PM (1 occurrences)
> Last logged: 8:51:02 PM
> 
> Input is a zero-length, empty document: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/aiounifi/interfaces/connectivity.py", line 175, in websocket
>     callback(message.data)
>   File "/usr/local/lib/python3.12/site-packages/aiounifi/interfaces/messages.py", line 56, in new_data
>     self.handler(orjson.loads(raw_bytes))
>                  ^^^^^^^^^^^^^^^^^^^^^^^
> orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)

**Comment by Kane610** [comment]
Thanks! This will be solved by https://github.com/Kane610/aiounifi/pull/587 in HASS 2024.2.2
