### ISSUE TITLE
Bad JSON data ''

### ISSUE THREAD

**Issue by bmos** [Kane610/aiounifi#603]
I am seeing this in my logs:

```
Logger: aiounifi.interfaces.messages
Source: components/unifi/controller.py:384
First occurred: 12:19:55 AM (28 occurrences)
Last logged: 12:23:10 PM

Bad JSON data ''
```

Let me know what further info I can give to help resolve it.

**Comment by Kane610** [comment]
Thanks for reporting! What versions of UniFi are you running

**Comment by bmos** [comment]
### UniFi
UniFi OS 3.2.12
Network 8.0.28

### Home Assistant
Hardware Home Assistant Yellow
Core 2024.2.4
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240207.1

**Comment by facetheheat** [comment]
Same here.

UniFi OS v3.2.12
Network v8.1.113
HA Core 2024.3.3
