### ISSUE TITLE
Add Support to un-/Block WLAN devices

### ISSUE THREAD

**Issue by PatrickOnGit** [Kane610/aiounifi#612]
Having older kids it would be great to block and unblock WLAN (phone) devices during night.
This is off course no security nor educational feature.
There might be other good reasons to block or unblock  a device.

Thank you for thinking about it

**Comment by Kane610** [comment]
Great suggestion! As it happens this gesture is already supported in Home Assistant 🎉

https://www.home-assistant.io/integrations/unifi/#block-network-access-for-clients

Just go into configure options on you unifi integration and select what clients you want entities for (the following pages with more detailed selections will be removed for this simpler configuration) and you should get block/unblock switches for you selected clients and additional entities as well.
