### ISSUE TITLE
Error on integration

### ISSUE THREAD

**Issue by Cippo2019** [Kane610/aiounifi#703]
Hi
thanks in advance for you great job

I am facing an old problem (maybe)
i have read some post but was solved in early HA version (from may).. if i correct understood

HA lateast version 7.4
Unifi 4.0.6

Unifi integration installed and configured with local user (admin)
On Unifi console I see logged user without problem (on timeline)

I am able to get all info from Gateway and switches but if i try to change, for example, POE port (in off) i get a lot of error like this

File "/usr/local/lib/python3.12/site-packages/aiounifi/interfaces/connectivity.py", line 143, in _request
    raise LoginRequired(f"Call {url} received 401 Unauthorized")
aiounifi.errors.LoginRequired: Call https://172.16.1.254:443/proxy/network/api/s/default/rest/device/6637f7e9b019 received 401 Unauthorized
During handling of the above exception, another exception occurred:
Traceback (most recent call last):

 finished with

ile "/usr/local/lib/python3.12/site-packages/aiounifi/interfaces/connectivity.py", line 167, in _request
    raise ResponseError(f"Call {url} received 429: {bytes_data!r}")
aiounifi.errors.ResponseError: Call https://172.16.1.254:443/api/auth/login received 429: b'{"code":"AUTHENTICATION_FAILED_LIMIT_REACHED","message":"You\'ve reached the login attempt limit","level":"debug"}'

I have already done to remove and re install integration 

like host i have put my local IP (internal one)
user and psw with admin right
port 443
ssl verification in no checkbox

thanks in advance

wbr
Tz

**Comment by Kane610** [comment]
Are you running the UCG ultra?

Issue reported here https://github.com/home-assistant/core/issues/122438#issuecomment-2269730143

I cant figure out what is the cause of it unfortunately

**Comment by Cippo2019** [comment]
Hi 
yes sorry i see now that post ... i confirm i have ultra
so i have no chances or do you think that maybe will be solved in the future ?
wbr

**Comment by Kane610** [comment]
If its possible to do the controls from the web interface then it is possible for the integration as well

**Comment by Cippo2019** [comment]
what do you mean ?
yes for console web i can enable or disable POE port for example
but from integration i get error like in the previous post

or maybe i didn't understand ? 

:-)

**Comment by Kane610** [comment]
Then it's fixable

**Comment by Cippo2019** [comment]
a ok , so i am really happy to hear :-)

thanks a lot again !

**Comment by Cippo2019** [comment]
Hi 
upgrade to 8.2 solved the problem 
thanks a lot

**Comment by Cippo2019** [comment]
closed
