### ISSUE TITLE
Stange behaviour

### ISSUE THREAD

**Issue by Cippo2019** [Kane610/aiounifi#713]
Hi
I wanted to ask, I apologize in advance if this is not the right place to report it because, after installing the native Unifi Network integration, I also find the broadlink inside the group. (see images)

It's not a real problem, but I'm curious.
Thanks

![unifi1](https://github.com/user-attachments/assets/9fd8efbe-3453-436e-9216-c3ea946a66fd)
![unifi2](https://github.com/user-attachments/assets/9340e172-349b-4860-8de6-5515ad75d969)

**Comment by Kane610** [comment]
Its just a reference to what integrations that device has entities belonging to

**Comment by Cippo2019** [comment]
but it also belongs to the Broadlink integration, the initial native one

![image](https://github.com/user-attachments/assets/4765b30e-a441-41dd-b346-d9f908349caa)

and if you click on

it goes here

![image](https://github.com/user-attachments/assets/51de5945-b580-4202-80d8-c63aeb83c341)

i dont understand which is the relation

**Comment by Cippo2019** [comment]
before installing UNIFI integration it was like this

![image](https://github.com/user-attachments/assets/457dd601-054e-43b9-b65a-4f4324d2776b)

**Comment by Kane610** [comment]
The relation is that the device tracker (from unifi) entity is connected to the device which also contain entities from broadlink integration

**Comment by Cippo2019** [comment]
I think I didn't understand.
I haven't made any changes to the tracker part of the devices yet.
So are you saying that it is correct and that it should be written like this?

**Comment by Kane610** [comment]
Seems perfectly normal to me

**Comment by Cippo2019** [comment]
for me no
before UNIFI i had broadlink integration like this

![image](https://github.com/user-attachments/assets/853f42ce-0a70-4e82-91b8-e1c5c4407dba)

you can see Broadkink native integrazion and the relative entity and so on
after UNIFI when you link you are directly moved to UNIFI and entity

to be honest i dont understand why the broadlnk device now is under UNIFI integration.

sorry for that, I am not so expert to be honest, i am just trying to understand the concept.

:-)
thanks again

**Comment by Kane610** [comment]
Its under both integrations

**Comment by Cippo2019** [comment]
ok 
it's not clear though, I tried to disable the tracker entity and it continues to show it under Unifi and no longer directly under its native integration (Broadlink)
In my opinion it's a bit misleading.
I don't want to continue to stress you out :-)
Thanks for the answers :-)
