### ISSUE TITLE
[QUESTION] Is there API or the HA integrated which can turn on off the LED light of the AP

### ISSUE THREAD

**Issue by Gatsby-Lee** [Kane610/aiounifi#714]
HI, Please this issue if this is not the right place.

I am wondering if there is any existing API ( or functionality ) or the HA integrated function which can turn on and off the LED lamp of the AP.

If it doesn't exist, can you covert this into a feature request?

Thank you
Gatsby

**Comment by Kane610** [comment]
There are attributes that probably does this

```
    led_override: str
    led_override_color: str
    led_override_color_brightness: int
```

But this is nothing I've looked into

**Comment by Gatsby-Lee** [comment]
> There are attributes that probably does this
> 
> ```
>     led_override: str
>     led_override_color: str
>     led_override_color_brightness: int
> ```
> 
> But this is nothing I've looked into

Thank you for pointing to the attributes.
I guess this might be the least important feature :)

**Comment by Gatsby-Lee** [comment]
> There are attributes that probably does this
> 
> ```
>     led_override: str
>     led_override_color: str
>     led_override_color_brightness: int
> ```
> 
> But this is nothing I've looked into

Ah. I have one more questions.
Does aiounifi has any functions that send a command API request to UniFi devices to change or update the current status?
Or, aiounifi only has functions that fetchs the information metrics?

Thank you

**Comment by Kane610** [comment]
Yes support was added for it in aiounifi https://github.com/Kane610/aiounifi/pull/593

But its not yet utilize by the integration

**Comment by Gatsby-Lee** [comment]
Thank you!!
