### ISSUE TITLE
Feature: Add check for new releases of controller software

### ISSUE THREAD

**Issue by Olen** [Kane610/aiounifi#97]
It wpuld be great to have a sensor in HA for "new version available" - both for the controller and other components.

The API that the controller itself is using to fetch the latest available software is
https://fw-update.ubnt.com/api/firmware?filter=eq~~product~~unifi-controller&filter=eq~~platform~~unix&filter=eq~~channel~~release&sort=-version&limit=1

It should be pretty trivial to compare this to what the controller is currently running.

I tried playing around with the url to get the latest version of different AP models too, but not success so far.

**Comment by Kane610** [comment]
Hello!

There is an attribute already exposed with next firmware that the device can upgrade to

https://github.com/Kane610/aiounifi/blob/2fcd0e807b83449df417e255eb45909bbc24492c/aiounifi/devices.py#L179

**Comment by Olen** [comment]
Ah. Thanks. I missed that.  It seems like it is not availabe in HA.  I might be looking at the wrong place, but in fact, I can't find any information about the Unifi-controller in HA at all.

**Comment by Kane610** [comment]
Its not implemented on home assistant side yet :)

**Comment by Kane610** [comment]
FW Upgrade support added to integration since a long time. Controller specific firmware is still unsure how to figure out. Closing this as device upgrade is supported.
